- name: play1
  hosts: local
  connection: local #run its own node no need credentials
  tasks:
  - name: play1 and task1
    ansible.builton.debug:
     msg: "Hello  from play1 and task1"

- name: play2
  hosts: local
  connection: local
  tasks:
  - name: play2 and task1
    ansible.builtin.debug:
     msg: "Hello fomr play2 and task1"
     

  