# - name: variable
#   hosts: local
#   connection: local
#   tasks:
#   - name: print the variables
#     ansible.builtin.debug:
#      msg:"Course is Devopsdaws82s,duration is 120 hours, trainer is Shivakumar"

# - name: variables
#   hosts: local
#   connection: local
#   vars: # PLAY level variables
#     COURSE: "DevOps with AWS"
#     DURATION: 120HRS
#     TRAINER: Sivakumar
#   tasks:
#   - name: print the variable
#     ansible.builtin.debug:
#       msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

- name: variableS
  hosts: local
  connection: local
  vars: #play level variables
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: shivakumar
  tasks:
  - name: print the variables
    vars:
    COURSE: Ansible
    ansible.builtin.debug:
      msg: "course is {{COURSE}},duration is {{DURATION}},trainer is {{TRAINER}}"
  - name: print the variables1
    ansible.builtin:debug:
      msg:  "course is {{COURSE}},duration is {{DURATION}},trainer is {{TRAINER}}"