- name: variables from promt
  hosts: local
  connection: local
  vars:promt:
  - name: COURSE
    promt: please enter your course name.?
  - name: DURATION
    promt: what is your course name.?
  - name: TRAINER
    prompt: what your trainer name.?
  tasks:
  - name: print the variables from prompt
    ansible.builtin.debug:
     msg: "course is {{COURSE}},Duration is{{DURATION}},trainer is {{TRAINER}}"
