- name: Datatypes variables for Devops ansible
  hosts: local
  connection: local
  vars:
    COURSE_NAME: "Devops with Aws"
    DURATION: 120HRS
    topics: #list
    - Linux
    - Ansible
    - Shell
    - Aws
    live: True #Boolean
    tools:
     cloud: aws
     ci: jenkins
     containerization: docker
tasks:
- name: "Devops with Aws ansible"
  ansible.builtin.debug:
   msg: "Hello course name is {{COURSE_NAME}}", Duration is : {{DURATION}}, topics are {{topics}},live is {{live}}, tools are {{tools}}
  
